### ISSUE TITLE
Timestamp format from IIDR-UE-KCOP

### ISSUE THREAD

**Issue by jonatasmielnik** [fketelaars/IIDR-UE-KCOP#6]
Hi Frank, how are you?

I'm using your IIDR-UE-KCOP, but I got in the code at KcopLiveAuditJson.java:

	/*
	 * Append the apply timestamp
	 */
	private void addApplyTimestamp(JsonObject kafkaAuditJson) {
		String timeStamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss.SSS000").format(new Date());
		kafkaAuditJson.addProperty(applyTimestampColumn, timeStamp);
	}

This bring me the format always with rounding, but in correct format. If I use the timestamp from IIDR, it bring me without the rounding but with an incorrect form:

"2018-06-29-07.42.53.936**336**" - Default from IIDR
"2018-06-29 07:40:56.446**000**" - Your UE KCOP

Is it possible change the rounding to bring the exactly time without the rounding?

**Comment by fketelaars** [comment]
Yes, I think we can change the apply timestamp to use java.time as we don't need to support Java 7 for the KCOP. I will look into this.

**Comment by fketelaars** [comment]
Changes have been committed. Please ensure you restart the CDC for Kafka engine after you have implemented the new JAR file.

**Comment by jonatasmielnik** [comment]
Hi Frank, that's running perfectly, thanks for your support
